pattern1 = Pattern.create(:name => "Toast & Marmalade", :theme => "Toast & Marmalade"),
pattern2 = Pattern.create(:name => "Cambridge Blue Toast", :theme => "Toast & Marmalade"),
pattern3 = Pattern.create(:name => "Blue Skies", :theme => "Toast & Marmalade"),
pattern4 = Pattern.create(:name => "Starry Toast", :theme => "Toast & Marmalade"),
pattern5 = Pattern.create(:name => "Polka Dot", :theme => "Polka Dot"),
pattern6 = Pattern.create(:name => "Spring Floral", :theme => "Polka Dot"),
pattern7 = Pattern.create(:name => "Starry Skies", :theme => "Blues"),
pattern8 = Pattern.create(:name => "Feather Wreath", :theme => "Blues"),
pattern9 = Pattern.create(:name => "Blue Shells", :theme => "Blues"),
pattern10 = Pattern.create(:name => "Utility", :theme => "Blues"),
pattern11 = Pattern.create(:name => "Stargazer Lillies", :theme => "Pinks"),
pattern12 = Pattern.create(:name => "Pink Hearts", :theme => "Pinks"),
pattern13 = Pattern.create(:name => "Pink Pansy", :theme => "Pinks"),
pattern14 = Pattern.create(:name => "Tiny Scattered Rose", :theme => "Pinks"),
pattern15 = Pattern.create(:name => "Love & Kisses", :theme => "Pinks")
pattern16 = Pattern.create(:name => "Wallflower", :theme => "Wallflower"),
pattern17 = Pattern.create(:name => "Rainbow Dots", :theme => "Wallflower"),
pattern18 = Pattern.create(:name => "Purple Pansy", :theme => "Wallflower"),
pattern19 = Pattern.create(:name => "Game Birds", :theme => "From Nature"),
pattern20 = Pattern.create(:name => "Flowers", :theme => "From Nature"),
pattern21 = Pattern.create(:name => "Vegetable Garden", :theme => "From Nature"),
pattern22 = Pattern.create (:name => "Dogs & Cats", :theme => "From Nature"),
pattern23 = Pattern.create(:name => "Dinosaurs", :theme => "Children's Patterns"),
pattern24 = Pattern.create(:name => "Dancing Mice", :theme => "Children's Patterns"),
pattern25 = Pattern.create(:name => "Halloween", :theme => "People & Places"),
pattern26 = Pattern.create(:name => "Kings & Queens", :theme => "People & Places"),
pattern27 = Pattern.create(:name => "City of Dreams", :theme => "People & Places"),
pattern28 = Pattern.create(:name => "Royal Mugs", :theme => "People & Places"),

piece1 = Piece.create(:name)
