pattern1 = Pattern.create(:name => "Toast & Marmalade", :colorway => "Toast & Marmalade"),
pattern2 = Pattern.create(:name => "Cambridge Blue Toast", :colorway => "Toast & Marmalade"),
pattern3 = Pattern.create(:name => "Blue Skies", :colorway => "Toast & Marmalade"),
pattern4 = Pattern.create(:name => "Polka Dot", :colorway => "Polka Dot"),
pattern5 = Pattern.create(:name => "Spring Floral", :colorway => "Polka Dot"),
pattern6 = Pattern.create(:name => "Starry Skies", :colorway => "Blues"),
pattern7 = Pattern.create(:name => "Feather Wreath", :colorway => "Blues"),
pattern8 = Pattern.create(:name => "Blue Shells", :colorway => "Blues"),
pattern9 = Pattern.create(:name => "Stargazer Lillies", :colorway => "Pinks"),
pattern10 = Pattern.create(:name => "Pink Hearts", :colorway => "Pinks"),
pattern11 = Pattern.create(:name => "Pink Pansy", :colorway => "Pinks"),
pattern12 = Pattern.create(:name => "Tiny Scattered Rose", :colorway => "Pinks"),
pattern13 = Pattern.create(:name => "Wallflower", :colorway => "Wallflower"),
pattern14 = Pattern.create(:name => "Rainbow Dots", :colorway => "Wallflower"),
pattern15 = Pattern.create(:name => "Purple Pansy", :colorway => "Wallflower"),
