pattern1 = Pattern.create(:name => "Toast & Marmalade", :colorway => "Toast & Marmalade"),
pattern2 = Pattern.create(:name => "Cambridge Blue Toast", :colorway => "Toast & Marmalade"),
pattern3 = Pattern.create(:name => "Blue Skies", :colorway => "Toast & Marmalade"),
pattern4 = Pattern.create(:name => "Starry Toast", :colorway => "Toast & Marmalade"),
pattern5 = Pattern.create(:name => "Polka Dot", :colorway => "Polka Dot"),
pattern6 = Pattern.create(:name => "Spring Floral", :colorway => "Polka Dot"),
pattern7 = Pattern.create(:name => "Starry Skies", :colorway => "Blues"),
pattern8 = Pattern.create(:name => "Feather Wreath", :colorway => "Blues"),
pattern9 = Pattern.create(:name => "Blue Shells", :colorway => "Blues"),
pattern10 = Pattern.create(:name => "Utility", :colorway => "Blues"),
pattern11 = Pattern.create(:name => "Stargazer Lillies", :colorway => "Pinks"),
pattern12 = Pattern.create(:name => "Pink Hearts", :colorway => "Pinks"),
pattern13 = Pattern.create(:name => "Pink Pansy", :colorway => "Pinks"),
pattern14 = Pattern.create(:name => "Tiny Scattered Rose", :colorway => "Pinks"),
pattern15 = Pattern.create(:name => "Love & Kisses", :colorway => "Pinks")
pattern16 = Pattern.create(:name => "Wallflower", :colorway => "Wallflower"),
pattern17 = Pattern.create(:name => "Rainbow Dots", :colorway => "Wallflower"),
pattern18 = Pattern.create(:name => "Purple Pansy", :colorway => "Wallflower"),
pattern19 = Pattern.create(:name => "Game Birds", :colorway => "From Nature"),
pattern20 = Pattern.create(:name => "Flowers", :colorway => "From Nature"),
pattern21 = Pattern.create(:name => "Vegetable Garden", :colorway => "From Nature"),
pattern22 = Pattern.create (:name => "Dogs & Cats", :colorway => "From Nature"),
pattern23 = Pattern.create(:name => "Dinosaurs", :colorway => "Children's Patterns"),
pattern24 = Pattern.create(:name => "Dancing Mice", :colorway => "Children's Patterns"),
pattern25 = Pattern.create(:name => "Halloween", :colorway => "People & Places"),
pattern26 = Pattern.create(:name => "Kings & Queens", :colorway => "People & Places"),
pattern27 = Pattern.create(:name => "City of Dreams", :colorway => "People & Places"),
pattern28 = Pattern.create(:name => "Royal Mugs", :colorway => "People & Places"),

piece1 = Piece.create(:name)
